#####################################################################

#     copyright 2019 (c) Michael Treanor <https://www.github.com/skeptycal>
#     MIT License <https://opensource.org/licenses/MIT>

default_language_version:
    python: python3.7
exclude: '^$'
fail_fast: false
repos:
    - repo: git://github.com/pre-commit/pre-commit-hooks
      rev: v3.1.0
      hooks:
          - id: check-added-large-files
          - id: check-byte-order-marker
          - id: check-docstring-first
          - id: check-case-conflict
          - id: check-json
          - id: check-merge-conflict
          - id: check-symlinks
          # -   id: check-yaml
          #    -   id: detect-aws-credentials
          - id: detect-private-key
          - id: end-of-file-fixer
          #   - id: flake8
          # -   id: pretty-format-json
          - id: requirements-txt-fixer
          - id: trailing-whitespace
    - repo: git://github.com/pre-commit/mirrors-pylint
      rev: v2.5.3
      hooks:
          - id: pylint
